/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UcetRouteImport } from './routes/ucet'
import { Route as KalkulackaRouteImport } from './routes/kalkulacka'
import { Route as CenyRouteImport } from './routes/ceny'
import { Route as IndexRouteImport } from './routes/index'

const UcetRoute = UcetRouteImport.update({
  id: '/ucet',
  path: '/ucet',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulackaRoute = KalkulackaRouteImport.update({
  id: '/kalkulacka',
  path: '/kalkulacka',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/ucet': typeof UcetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/ucet': typeof UcetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/ucet': typeof UcetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ceny' | '/kalkulacka' | '/ucet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ceny' | '/kalkulacka' | '/ucet'
  id: '__root__' | '/' | '/ceny' | '/kalkulacka' | '/ucet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenyRoute: typeof CenyRoute
  KalkulackaRoute: typeof KalkulackaRoute
  UcetRoute: typeof UcetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ucet': {
      id: '/ucet'
      path: '/ucet'
      fullPath: '/ucet'
      preLoaderRoute: typeof UcetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulacka': {
      id: '/kalkulacka'
      path: '/kalkulacka'
      fullPath: '/kalkulacka'
      preLoaderRoute: typeof KalkulackaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenyRoute: CenyRoute,
  KalkulackaRoute: KalkulackaRoute,
  UcetRoute: UcetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
