/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrihlasenieRouteImport } from './routes/prihlasenie'
import { Route as PlatbaRouteImport } from './routes/platba'
import { Route as OchranaUdajovRouteImport } from './routes/ochrana-udajov'
import { Route as ObchodnePodmienkyRouteImport } from './routes/obchodne-podmienky'
import { Route as KalkulackaRouteImport } from './routes/kalkulacka'
import { Route as CenyRouteImport } from './routes/ceny'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUcetRouteImport } from './routes/_authenticated/ucet'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const PrihlasenieRoute = PrihlasenieRouteImport.update({
  id: '/prihlasenie',
  path: '/prihlasenie',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatbaRoute = PlatbaRouteImport.update({
  id: '/platba',
  path: '/platba',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaUdajovRoute = OchranaUdajovRouteImport.update({
  id: '/ochrana-udajov',
  path: '/ochrana-udajov',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodnePodmienkyRoute = ObchodnePodmienkyRouteImport.update({
  id: '/obchodne-podmienky',
  path: '/obchodne-podmienky',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulackaRoute = KalkulackaRouteImport.update({
  id: '/kalkulacka',
  path: '/kalkulacka',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUcetRoute = AuthenticatedUcetRouteImport.update({
  id: '/ucet',
  path: '/ucet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/platba': typeof PlatbaRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/ucet': typeof AuthenticatedUcetRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/platba': typeof PlatbaRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/ucet': typeof AuthenticatedUcetRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ceny': typeof CenyRoute
  '/kalkulacka': typeof KalkulackaRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/ochrana-udajov': typeof OchranaUdajovRoute
  '/platba': typeof PlatbaRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/_authenticated/ucet': typeof AuthenticatedUcetRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceny'
    | '/kalkulacka'
    | '/obchodne-podmienky'
    | '/ochrana-udajov'
    | '/platba'
    | '/prihlasenie'
    | '/ucet'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ceny'
    | '/kalkulacka'
    | '/obchodne-podmienky'
    | '/ochrana-udajov'
    | '/platba'
    | '/prihlasenie'
    | '/ucet'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ceny'
    | '/kalkulacka'
    | '/obchodne-podmienky'
    | '/ochrana-udajov'
    | '/platba'
    | '/prihlasenie'
    | '/_authenticated/ucet'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CenyRoute: typeof CenyRoute
  KalkulackaRoute: typeof KalkulackaRoute
  ObchodnePodmienkyRoute: typeof ObchodnePodmienkyRoute
  OchranaUdajovRoute: typeof OchranaUdajovRoute
  PlatbaRoute: typeof PlatbaRoute
  PrihlasenieRoute: typeof PrihlasenieRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prihlasenie': {
      id: '/prihlasenie'
      path: '/prihlasenie'
      fullPath: '/prihlasenie'
      preLoaderRoute: typeof PrihlasenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platba': {
      id: '/platba'
      path: '/platba'
      fullPath: '/platba'
      preLoaderRoute: typeof PlatbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-udajov': {
      id: '/ochrana-udajov'
      path: '/ochrana-udajov'
      fullPath: '/ochrana-udajov'
      preLoaderRoute: typeof OchranaUdajovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodne-podmienky': {
      id: '/obchodne-podmienky'
      path: '/obchodne-podmienky'
      fullPath: '/obchodne-podmienky'
      preLoaderRoute: typeof ObchodnePodmienkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulacka': {
      id: '/kalkulacka'
      path: '/kalkulacka'
      fullPath: '/kalkulacka'
      preLoaderRoute: typeof KalkulackaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ucet': {
      id: '/_authenticated/ucet'
      path: '/ucet'
      fullPath: '/ucet'
      preLoaderRoute: typeof AuthenticatedUcetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUcetRoute: typeof AuthenticatedUcetRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUcetRoute: AuthenticatedUcetRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CenyRoute: CenyRoute,
  KalkulackaRoute: KalkulackaRoute,
  ObchodnePodmienkyRoute: ObchodnePodmienkyRoute,
  OchranaUdajovRoute: OchranaUdajovRoute,
  PlatbaRoute: PlatbaRoute,
  PrihlasenieRoute: PrihlasenieRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
